version: "3.9"

services:
  postgres:
    image: postgres:14-alpine
    environment:
      POSTGRES_DB: "shop"
      POSTGRES_USER: "p_user"
      POSTGRES_PASSWORD: "p_password"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./volumes/postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  cassandra:
    image: cassandra:4.0
    ports:
      - "9042:9042"
    volumes:
      - ./volumes/cassandra:/var/lib/cassandra
    environment:
      - CASSANDRA_CLUSTER_NAME=shop
